package main

func main() {
	// goroutineExample()
	// ignoredGoroutineExample()
	// channelExample()
	// channelIterationExample()
	// channelDirectionExample()
	// selectExample()
	// selectSendExample()
	ioPipeExample()
	// syncexamples.WaitGroupExample()
	// syncexamples.ModernWaitGroupExample()
	// syncexamples.WaitGroupFetchExample()
	// syncexamples.MutexExample()
	// syncexamples.RWMutexExample()
	// syncexamples.OnceExample()
	// syncexamples.PoolExample()
	// syncexamples.CondExample()
	// syncexamples.AtomicExample()
	// contextTimeoutExample()
	// contextCancellationExample()
	// contextValuesExample()
	// errorexamples.DeadlockExample()
	// errorexamples.RaceConditionExample()
	// errorexamples.GoroutineLeakExample()
	// patterns.FanOutFanInExample()
	// patterns.GeneratorExample()
	// patterns.PipelineExample()
	// patterns.WorkerPoolExample()
	// patterns.SemaphoreExample()
}
